// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs_4-NoxYEsFaAoMAnLYMD-1B-vJ6yzYs',
    appId: '1:736869357654:web:3d677f8e8bb6f2f78003f7',
    messagingSenderId: '736869357654',
    projectId: 'flutter-saferoads',
    authDomain: 'flutter-saferoads.firebaseapp.com',
    storageBucket: 'flutter-saferoads.firebasestorage.app',
    measurementId: 'G-WY19DNMX4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzPGGwaIQQ5UCpBccRRwdLF2YZi1vA02I',
    appId: '1:736869357654:android:014346f616d6e6b28003f7',
    messagingSenderId: '736869357654',
    projectId: 'flutter-saferoads',
    storageBucket: 'flutter-saferoads.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQQVUlm7XdTaqR59qojvFRY7uRyUPt0DU',
    appId: '1:736869357654:ios:c30ab17221684a738003f7',
    messagingSenderId: '736869357654',
    projectId: 'flutter-saferoads',
    storageBucket: 'flutter-saferoads.firebasestorage.app',
    iosBundleId: 'com.example.safeRoads',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQQVUlm7XdTaqR59qojvFRY7uRyUPt0DU',
    appId: '1:736869357654:ios:c30ab17221684a738003f7',
    messagingSenderId: '736869357654',
    projectId: 'flutter-saferoads',
    storageBucket: 'flutter-saferoads.firebasestorage.app',
    iosBundleId: 'com.example.safeRoads',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs_4-NoxYEsFaAoMAnLYMD-1B-vJ6yzYs',
    appId: '1:736869357654:web:096d9169f60769298003f7',
    messagingSenderId: '736869357654',
    projectId: 'flutter-saferoads',
    authDomain: 'flutter-saferoads.firebaseapp.com',
    storageBucket: 'flutter-saferoads.firebasestorage.app',
    measurementId: 'G-L13620MCFX',
  );
}
