class LanguageConfig {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      // About
      'why': 'Why',
      'whyBody': 'The expansion of roads and traffic systems globally presents significant challenges to biodiversity. While roads offer benefits to humans, they also contribute to a growing biodiversity crisis by fragmenting ecosystems, altering natural landscapes, and creating "barrier effects" that impede wildlife movement. One of the most immediate impacts of roads on wildlife is the high mortality caused by collisions with vehicles, endangering many species. \nTo address this issue, the SafeRoads mobile application provides a platform to visualize a predictive model of roadkill risk. The system integrates a navigation feature that assesses the likelihood of animal presence along road segments, alerts users, and recommends safer routes to mitigate the risk of Wildlife-Vehicle Collisions (WVCs).',
      'how': 'How',
      'howBody': 'The SafeRoads mobile application accesses the results from a predictive, daily updated roadkill risk machine learning model. This model assesses roadkill probability based on conditions such as surrounding land use, weather, season, and time of day. The application visualizes this information through a user-friendly platform, providing dynamic roadkill risk insights across different road segments. By notifying drivers of high-risk areas and suggesting alternative routes, SafeRoads aims to reduce the incidence of roadkill, similar to how navigation tools like Waze or Google Maps re-route based on traffic conditions.',
      'who': 'Who',
      'whoBody': 'This work was conducted as part of the academic project SafeRoads, developed by Lara Ângelo (LASIGE), Fernando Ascensão (CE3C), Ana Paula Afonso (LASIGE), Carlos Duarte (LASIGE). The project is entirely owned by the Faculty of Sciences, University of Lisbon.',
      // Profile & Edit Profile w/ Snackbars
      'username': 'Loading...',
      'country': 'Loading...',
      'level': 'Level',
      'totalKm': 'Total km',
      'places': 'Places',
      'signOut': 'Sign Out',
      'signOutConfirmation': 'Are you sure you want to sign out?',
      'cancel': 'Cancel',
      'deleteAccount': 'Delete Account',
      'enterPassword': 'Please enter your password to confirm account deletion.',
      'password': 'Password',
      'delete': 'Delete',
      'passwordRequired': 'Password is required to delete your account.',
      'updateFailed': 'Update failed',
      'statistics': 'Statistics',
      'viewRouteHistory': 'View route history >',
      'preferences': 'Preferences',
      'allowNotifications': 'Allow notifications',
      'onlyLowRisk': 'Only low risk route',
      'changeRoute': 'Change route automatically',
      'unitMeasure': 'Unit of measure',
      'riskAlertDistance': 'Risk alert distance',
      'what': 'What is this?',
      'riskAlertDistanceInfo': 'This setting determines the distance at which you will receive a notification about upcoming risk zones. Choose a smaller distance for precise alerts or a larger distance for early warnings.',
      'reRouteAlertDistance': 'Re-route alert distance',
      'reRouteAlertDistanceInfo': 'This setting determines the distance at which you will receive a notification about upcoming Re-route opportunities. Choose a smaller distance for precise alerts or a larger distance for early warnings.',
      'language': 'Language',
      'speciesForAlerts': 'Select Species for Alerts',
      'settings': 'Settings',
      'editProfile': 'Edit Profile',
      'info': 'Alert Information',
      'amphibians': 'Amphibians',
      'reptiles': 'Reptiles',
      'hedgehogs': 'Hedgehogs',
      'enterUsername': 'Username',
      'enterEmail': 'Email',
      'enterCountry': 'Country',
      'passwordUpdated': 'Password updated successfully!',
      'errorFetchingProfile': 'Error fetching profile:',
      'profileUpdated': 'Profile updated successfully!',
      'errorUpdatingProfile': 'Error updating profile:',
      'selectProfile': 'Select Profile Image',
      'currentPass': 'Current Password',
      'enterCurrent': 'Enter current password',
      'newPass': 'New Password',
      'enterNew': 'Enter new password',
      'update': 'Update',
      'profileDeleted': 'Account deleted successfully.',
      // Home
      'errorFetchingRoute': 'Error fetching route:',
      'failFetchingRoute': 'Failed to fetch route',
      'errorFetchingCoordinates': 'Error fetching coordinates',
      'errorFetchingSuggestions': 'Error fetching suggestions',
      'errorFetchingPreferences': 'Error fetching preferences', 
      'enterDestination': 'Enter Destination',
      'setDestination': 'Set Destination',
      'highProbability': 'High probability of encountering',
      'mediumProbability': 'Medium probability of encountering',
      'unknown': 'Unknown',
      'switchRoute': 'Switch Route',
      'start': 'Start',
      // Login
      'welcome': 'Welcome back!\nGlad to see you, Again!',
      'inputEmail': 'Enter your email',
      'pleaseEmail': 'Please enter your email',
      'userPass': 'Enter your password',
      'pleasePass': 'Please enter your password',
      'forgotPass': 'Forgot Password?',
      'login': 'Login',
      'noAccount': 'Don’t have an account? ',
      'registerNow': 'Register Now',
      // Register
      'helloRegister': 'Hello! \nRegister to get started',
      'pass': 'Password',
      'confirmPass': 'Confirm password',
      'register': 'Register',
      'accountAlready': 'Already have an account? ',
      'loginNow': 'Login Now',
      // Navigation Bar
      'about': 'About',
      'navigation': 'Navigation',
      'profile': 'Profile',
      // Navigation
      'invalidTime': 'Invalid travel time format.',
      'errorFetchingTime': 'Error calculating arrival time',
      'highRiskMsgTitle': '🚨 High Risk for',
      'highRiskMsgBody': 'Attention! High risk of the following species ahead',
      'stayAlert': 'Slow down and stay alert!',
      'mediumRiskMsgTitle': '⚠️ Caution',
      'atRisk': 'at Risk',
      'mediumRiskMsgBody': 'Be careful! Medium risk of the following species nearby',
      'caution': 'Proceed with caution.',
      'warning': 'WARNING: You are currently in a high-risk zone for the following species',
      'riskZoneHere': 'You are now in an area with medium risk for the following species',
      'wrongRouteMsgTitle': '🔃 Wrong Route!',
      'wrongRouteMsgBody': 'You are off the planned route.',
      'sameTimeMsg': 'Switch route! It will take the same time but with less risk.',
      'changeRouteMsg': 'The alternative route has less risk. Consider changing the route.',
      'altRouteTitle': '🚧 Alternative Route Recommended!',
      'destinationReached': 'Destination Reached!',
      // Auth Controller
      'allFields': 'All fields are required.',
      'passNoMatch': 'Passwords do not match.',
      'emailAndPassRequired': 'Email and Password are required.',
      'error': 'Error',
      // Profile Controller
      'noUser': 'No user is currently signed in.',
      // Notifications
      'reRouteButton': 'Re-route',
      'ignoreButton': 'Ignore',
    },
    'pt': {
      // About
      'why': 'Porquê',
      'whyBody': 'A expansão das estradas e dos sistemas de tráfego a nível global representa desafios significativos para a biodiversidade. Embora as estradas ofereçam benefícios para os seres humanos, também contribuem para uma crise crescente da biodiversidade, fragmentando ecossistemas, alterando paisagens naturais e criando “efeitos de barreira” que dificultam o movimento da vida selvagem. Um dos impactos mais imediatos das estradas sobre os animais é a elevada mortalidade causada por colisões com veículos, colocando muitas espécies em risco.\nPara enfrentar este problema, a aplicação móvel SafeRoads oferece uma plataforma que visualiza um modelo preditivo de risco de atropelamento de fauna. O sistema integra uma funcionalidade de navegação que avalia a probabilidade de presença de animais ao longo de segmentos rodoviários, alerta os utilizadores e recomenda rotas mais seguras para mitigar o risco de colisões com a vida selvagem (WVCs).',
      'how': 'Como',
      'howBody': 'A aplicação móvel SafeRoads acede aos resultados de um modelo preditivo de risco de atropelamento, atualizado diariamente. Este modelo avalia a probabilidade de ocorrência de atropelamentos com base em fatores como o uso do solo envolvente, condições meteorológicas, estação do ano e hora do dia. A aplicação visualiza esta informação através de uma interface intuitiva, fornecendo perceções dinâmicas sobre o risco de atropelamento em diferentes segmentos rodoviários. Ao notificar os condutores sobre zonas de elevado risco e sugerir rotas alternativas, o SafeRoads pretende reduzir a ocorrência de atropelamentos, de forma semelhante a como o Waze ou o Google Maps redirecionam o tráfego com base nas condições da estrada.',
      'who': 'Quem',
      'whoBody': 'Este trabalho foi desenvolvido no âmbito do projeto académico SafeRoads, por Lara Ângelo (LASIGE), Fernando Ascensão (CE3C), Ana Paula Afonso (LASIGE) e Carlos Duarte (LASIGE). O projeto é propriedade exclusiva da Faculdade de Ciências da Universidade de Lisboa.',
      // Profile & Edit Profile w/ Snackbars
      'username': 'Carregando...',
      'country': 'Carregando...',
      'level': 'Nível',
      'totalKm': 'Total km',
      'places': 'Lugares',
      'signOut': 'Sair',
      'signOutConfirmation': 'Tem certeza de que deseja sair?',
      'cancel': 'Cancelar',
      'deleteAccount': 'Excluir conta',
      'enterPassword': 'Digite sua senha para confirmar a exclusão da conta.',
      'password': 'Senha',
      'delete': 'Excluir',
      'passwordRequired': 'A senha é necessária para excluir sua conta.',
      'updateFailed': 'Falha na atualização',
      'statistics': 'Estatísticas',
      'viewRouteHistory': 'Ver histórico de rotas >',
      'preferences': 'Preferências',
      'allowNotifications': 'Permitir notificações',
      'onlyLowRisk': 'Apenas rotas de baixo risco',
      'changeRoute': 'Alterar rota automaticamente',
      'unitMeasure': 'Unidade de medida',
      'riskAlertDistance': 'Distância do alerta de risco',
      'what': 'O que é isso?',
      'riskAlertDistanceInfo': 'Esta configuração determina a distância na qual você receberá uma notificação sobre zonas de risco próximas. Escolha uma distância menor para alertas precisos ou uma maior para avisos antecipados.',
      'reRouteAlertDistance': 'Distância do alerta de re-rota',
      'reRouteAlertDistanceInfo': 'Esta configuração determina a distância na qual você receberá uma notificação sobre oportunidades de re-rota próximas. Escolha uma distância menor para alertas precisos ou uma maior para avisos antecipados.',
      'language': 'Idioma',
      'speciesForAlerts': 'Selecionar espécies para alertas',
      'settings': 'Configurações',
      'editProfile': 'Editar perfil',
      'info' : 'Informação do Alerta',
      'amphibians': 'Anfíbios',
      'reptiles': 'Répteis',
      'hedgehogs': 'Ouriços',
      'enterUsername': 'Nome de utilizador',
      'enterEmail': 'Email',
      'enterCountry': 'País',
      'passwordUpdated': 'Senha atualizada com sucesso!',
      'errorFetchingProfile': 'Erro ao buscar o perfil:',
      'profileUpdated': 'Perfil atualizado com sucesso!',
      'errorUpdatingProfile': 'Erro ao atualizar o perfil:',
      'selectProfile': 'Selecionar imagem de perfil',
      'currentPass': 'Senha atual',
      'enterCurrent': 'Digite a senha atual',
      'newPass': 'Nova senha',
      'enterNew': 'Digite a nova senha',
      'update': 'Atualizar',
      'profileDeleted': 'Conta excluída com sucesso.',
      // Home
      "errorFetchingRoute": "Erro ao obter rota:",
      "failFetchingRoute": "Falha ao obter rota",
      "errorFetchingCoordinates": "Erro ao obter coordenadas",
      "errorFetchingSuggestions": "Erro ao obter sugestões",
      "errorFetchingPreferences": "Erro ao obter preferências",
      "enterDestination": "Digite o destino",
      "setDestination": "Definir destino",
      "highProbability": "Alta probabilidade de encontrar",
      "mediumProbability": "Média probabilidade de encontrar",
      "unknown": "Desconhecido",
      "switchRoute": "Alterar rota",
      // Login
      "start": "Iniciar",
      'welcome': 'Bem-vindo de volta!\nQue bom vê-lo novamente!',
      'inputEmail': 'Digite o seu e-mail',
      'pleaseEmail': 'Por favor, insira o seu e-mail',
      'userPass': 'Digite a sua senha',
      'pleasePass': 'Por favor, insira a sua senha',
      'forgotPass': 'Esqueceu-se da senha?',
      'login': 'Entrar',
      'noAccount': 'Não tem uma conta? ',
      'registerNow': 'Cadastre-se agora',
      // Register
      'helloRegister': 'Olá! \nCadastre-se para começar',
      'pass': 'Senha',
      'confirmPass': 'Confirmar senha',
      'register': 'Cadastrar',
      'accountAlready': 'Já tem uma conta? ',
      'loginNow': 'Entrar agora',
      // Navigation Bar
      'about': 'Sobre',
      'navigation': 'Navegação',
      'profile': 'Perfil',
      // Navigation
      'invalidTime': 'Formato de tempo de viagem inválido.',
      'errorFetchingTime': 'Erro ao calcular o tempo de chegada',
      'highRiskMsgTitle': '🚨 Alto Risco para',
      'highRiskMsgBody': 'Atenção! Alto risco das seguintes espécies à frente',
      'stayAlert': 'Reduza a velocidade e fique atento!',
      'mediumRiskMsgTitle': '⚠️ Atenção',
      'atRisk': 'em Risco',
      'mediumRiskMsgBody': 'Cuidado! Risco médio das seguintes espécies nas proximidades',
      'caution': 'Prossiga com cautela.',
      'warning': 'AVISO: Você está em uma zona de alto risco para as seguintes espécies',
      'riskZoneHere': 'Você está agora em uma área com risco médio para as seguintes espécies',
      'wrongRouteMsgTitle': '🔃 Rota Errada!',
      'wrongRouteMsgBody': 'Você saiu da rota planejada.',
      'sameTimeMsg': 'Mude de rota! Levará o mesmo tempo, mas com menos risco.',
      'changeRouteMsg': 'A rota alternativa tem menos risco. Considere mudar de rota.',
      'altRouteTitle': '🚧 Rota Alternativa Recomendada!',
      'destinationReached': 'Destino Alcançado!',
      // Auth Controller
      "allFields": "Todos os campos são obrigatórios.",
      "passNoMatch": "As senhas não coincidem.",
      "emailAndPassRequired": "Email e senha são obrigatórios.",
      "error": "Erro",
      // Profile Controller
      "noUser": "Nenhum usuário está atualmente conectado.",
      // Notifications
      "reRouteButton": "Redirecionar",
      "ignoreButton": "Ignorar"
    },
    'es': {
      // About
      'why': 'Por qué',
      'whyBody': 'La expansión de carreteras y sistemas de tráfico a nivel mundial representa desafíos significativos para la biodiversidad. Aunque las carreteras ofrecen beneficios para los humanos, también contribuyen a una creciente crisis de biodiversidad al fragmentar ecosistemas, alterar paisajes naturales y crear “efectos barrera” que dificultan el movimiento de la fauna. Uno de los impactos más inmediatos es la alta mortalidad de animales causada por colisiones con vehículos, lo que pone en peligro a muchas especies.\nPara abordar este problema, la aplicación móvil SafeRoads proporciona una plataforma que visualiza un modelo predictivo del riesgo de atropellos de fauna. El sistema integra una función de navegación que evalúa la probabilidad de presencia de animales en los tramos de carretera, alerta a los usuarios y recomienda rutas más seguras para mitigar el riesgo de colisiones con fauna silvestre (WVCs).',
      'how': 'Cómo',
      'howBody': 'La aplicación móvil SafeRoads accede a los resultados de un modelo predictivo de riesgo de atropello, actualizado diariamente. Este modelo evalúa la probabilidad de atropello en función de condiciones como el uso del suelo, el clima, la estación del año y la hora del día. La aplicación visualiza esta información a través de una interfaz fácil de usar, proporcionando información dinámica sobre el riesgo de atropello en distintos tramos de carretera. Al notificar a los conductores sobre zonas de alto riesgo y sugerir rutas alternativas, SafeRoads pretende reducir la incidencia de atropellos, de forma similar a cómo Waze o Google Maps redirigen según el tráfico.',
      'who': 'Quiénes',
      'whoBody': 'Este trabajo fue realizado como parte del proyecto académico SafeRoads, desarrollado por Lara Ângelo (LASIGE), Fernando Ascensão (CE3C), Ana Paula Afonso (LASIGE) y Carlos Duarte (LASIGE). El proyecto es propiedad exclusiva de la Facultad de Ciencias de la Universidad de Lisboa.',
      // Profile & Edit Profile w/ Snackbars
      'username': 'Cargando...',
      'country': 'Cargando...',
      'level': 'Nivel',
      'totalKm': 'Kilómetros totales',
      'places': 'Lugares',
      'signOut': 'Cerrar sesión',
      'signOutConfirmation': '¿Estás seguro de que deseas cerrar sesión?',
      'cancel': 'Cancelar',
      'deleteAccount': 'Eliminar cuenta',
      'enterPassword': 'Introduce tu contraseña para confirmar la eliminación de la cuenta.',
      'password': 'Contraseña',
      'delete': 'Eliminar',
      'passwordRequired': 'Se requiere contraseña para eliminar tu cuenta.',
      'updateFailed': 'Error en la actualización',
      'statistics': 'Estadísticas',
      'viewRouteHistory': 'Ver historial de rutas >',
      'preferences': 'Preferencias',
      'allowNotifications': 'Permitir notificaciones',
      'onlyLowRisk': 'Solo rutas de bajo riesgo',
      'changeRoute': 'Cambiar ruta automáticamente',
      'unitMeasure': 'Unidad de medida',
      'riskAlertDistance': 'Distancia de alerta de riesgo',
      'what': '¿Qué es esto?',
      'riskAlertDistanceInfo': 'Esta configuración determina la distancia a la que recibirás una notificación sobre zonas de riesgo próximas. Elige una distancia menor para alertas precisas o una mayor para advertencias anticipadas.',
      'reRouteAlertDistance': 'Distancia de alerta de re-ruta',
      'reRouteAlertDistanceInfo': 'Esta configuración determina la distancia a la que recibirás una notificación sobre oportunidades de re-ruta próximas. Elige una distancia menor para alertas precisas o una mayor para advertencias anticipadas.',
      'language': 'Idioma',
      'speciesForAlerts': 'Seleccionar especies para alertas',
      'settings': 'Configuraciones',
      'editProfile': 'Editar perfil',
      'info' : 'Información de Alerta',
      'amphibians': 'Anfibios',
      'reptiles': 'Reptiles',
      'hedgehogs': 'Erizos',
      'enterUsername': 'Nombre de usuario',
      'enterEmail': 'Correo electrónico',
      'enterCountry': 'País',
      'passwordUpdated': '¡Contraseña actualizada con éxito!',
      'errorFetchingProfile': 'Error al obtener el perfil:',
      'profileUpdated': '¡Perfil actualizado con éxito!',
      'errorUpdatingProfile': 'Error al actualizar el perfil:',
      'selectProfile': 'Seleccionar imagen de perfil',
      'currentPass': 'Contraseña actual',
      'enterCurrent': 'Ingresa la contraseña actual',
      'newPass': 'Nueva contraseña',
      'enterNew': 'Ingresa la nueva contraseña',
      'update': 'Actualizar',
      'profileDeleted': 'Cuenta eliminada con éxito.',
      // Home
      "errorFetchingRoute": "Error al obtener la ruta:",
      "failFetchingRoute": "Error al obtener la ruta",
      "errorFetchingCoordinates": "Error al obtener coordenadas",
      "errorFetchingSuggestions": "Error al obtener sugerencias",
      "errorFetchingPreferences": "Error al obtener preferencias",
      "enterDestination": "Ingrese destino",
      "setDestination": "Establecer destino",
      "highProbability": "Alta probabilidad de encontrar",
      "mediumProbability": "Probabilidad media de encontrar",
      "unknown": "Desconocido",
      "switchRoute": "Cambiar ruta",
      "start": "Iniciar",
      // Login
      'welcome': '¡Bienvenido de nuevo!\n¡Qué bueno verte otra vez!',
      'inputEmail': 'Ingresa tu correo electrónico',
      'pleaseEmail': 'Por favor, ingresa tu correo electrónico',
      'userPass': 'Ingresa tu contraseña',
      'pleasePass': 'Por favor, ingresa tu contraseña',
      'forgotPass': '¿Olvidaste tu contraseña?',
      'login': 'Iniciar sesión',
      'noAccount': '¿No tienes una cuenta? ',
      'registerNow': 'Regístrate ahora',
      // Register
      'helloRegister': '¡Hola! \nRegístrate para empezar',
      'pass': 'Contraseña',
      'confirmPass': 'Confirmar contraseña',
      'register': 'Registrarse',
      'accountAlready': '¿Ya tienes una cuenta? ',
      'loginNow': 'Inicia sesión ahora',
      // Navigation Bar
      'about': 'Acerca de',
      'navigation': 'Navegación',
      'profile': 'Perfil',
      // Navigation
      'invalidTime': 'Formato de tiempo de viaje inválido.',
      'errorFetchingTime': 'Error al calcular el tiempo de llegada',
      'highRiskMsgTitle': '🚨 Alto Riesgo para',
      'highRiskMsgBody': '¡Atención! Alto riesgo de las siguientes especies adelante',
      'stayAlert': '¡Reduce la velocidad y mantente alerta!',
      'mediumRiskMsgTitle': '⚠️ Precaución',
      'atRisk': 'en Riesgo',
      'mediumRiskMsgBody': '¡Ten cuidado! Riesgo medio de las siguientes especies cerca',
      'caution': 'Procede con precaución.',
      'warning': 'ADVERTENCIA: Estás en una zona de alto riesgo para las siguientes especies',
      'riskZoneHere': 'Ahora estás en un área con riesgo medio para las siguientes especies',
      'wrongRouteMsgTitle': '🔃 ¡Ruta Incorrecta!',
      'wrongRouteMsgBody': 'Te has desviado de la ruta planificada.',
      'sameTimeMsg': '¡Cambia de ruta! Tomará el mismo tiempo pero con menos riesgo.',
      'changeRouteMsg': 'La ruta alternativa tiene menos riesgo. Considera cambiar de ruta.',
      'altRouteTitle': '🚧 ¡Ruta Alternativa Recomendada!',
      'destinationReached': '¡Destino Alcanzado!',
      // Auth Controller
      "allFields": "Todos los campos son obligatorios.",
      "passNoMatch": "Las contraseñas no coinciden.",
      "emailAndPassRequired": "Correo electrónico y contraseña son obligatorios.",
      "error": "Error",
      // Profile Controller
      "noUser": "Ningún usuario ha iniciado sesión.",
      // Notifications
      "reRouteButton": "Redirigir",
      "ignoreButton": "Ignorar"
    },
  };

  // Get the localized string based on selected language
  static String getLocalizedString(String languageCode, String key) {
    return translations[languageCode]?[key] ?? key;
  }
}
