class LanguageConfig {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      // About
      'why': 'Why',
      'how': 'How',
      'who': 'Who',
      // Profile & Edit Profile w/ Snackbars
      'username': 'Loading...',
      'country': 'Loading...',
      'level': 'Level',
      'totalKm': 'Total km',
      'places': 'Places',
      'signOut': 'Sign Out',
      'signOutConfirmation': 'Are you sure you want to sign out?',
      'cancel': 'Cancel',
      'deleteAccount': 'Delete Account',
      'enterPassword': 'Please enter your password to confirm account deletion.',
      'password': 'Password',
      'delete': 'Delete',
      'passwordRequired': 'Password is required to delete your account.',
      'updateFailed': 'Update failed',
      'statistics': 'Statistics',
      'viewRouteHistory': 'View route history >',
      'preferences': 'Preferences',
      'allowNotifications': 'Allow notifications',
      'onlyLowRisk': 'Only low risk route',
      'changeRoute': 'Change route automatically',
      'unitMeasure': 'Unit of measure',
      'riskAlertDistance': 'Risk alert distance',
      'what': 'What is this?',
      'riskAlertDistanceInfo': 'This setting determines the distance at which you will receive a notification about upcoming risk zones. Choose a smaller distance for precise alerts or a larger distance for early warnings.',
      'reRouteAlertDistance': 'Re-route alert distance',
      'reRouteAlertDistanceInfo': 'This setting determines the distance at which you will receive a notification about upcoming Re-route opportunities. Choose a smaller distance for precise alerts or a larger distance for early warnings.',
      'language': 'Language',
      'speciesForAlerts': 'Select Species for Alerts',
      'settings': 'Settings',
      'editProfile': 'Edit Profile',
      'info': 'Information',
      'amphibians': 'Amphibians',
      'reptiles': 'Reptiles',
      'hedgehogs': 'Hedgehogs',
      'enterUsername': 'Username',
      'enterEmail': 'Email',
      'enterCountry': 'Country',
      'passwordUpdated': 'Password updated successfully!',
      'errorFetchingProfile': 'Error fetching profile:',
      'profileUpdated': 'Profile updated successfully!',
      'errorUpdatingProfile': 'Error updating profile:',
      'selectProfile': 'Select Profile Image',
      'currentPass': 'Current Password',
      'enterCurrent': 'Enter current password',
      'newPass': 'New Password',
      'enterNew': 'Enter new password',
      'update': 'Update',
      'profileDeleted': 'Account deleted successfully.',
      // Home
      'errorFetchingRoute': 'Error fetching route:',
      'failFetchingRoute': 'Failed to fetch route',
      'errorFetchingCoordinates': 'Error fetching coordinates',
      'errorFetchingSuggestions': 'Error fetching suggestions',
      'errorFetchingPreferences': 'Error fetching preferences', 
      'enterDestination': 'Enter Destination',
      'setDestination': 'Set Destination',
      'highProbability': 'High probability of encountering',
      'mediumProbability': 'Medium probability of encountering',
      'unknown': 'Unknown',
      'switchRoute': 'Switch Route',
      'start': 'Start',
      // Login
      'welcome': 'Welcome back!\nGlad to see you, Again!',
      'inputEmail': 'Enter your email',
      'pleaseEmail': 'Please enter your email',
      'userPass': 'Enter your password',
      'pleasePass': 'Please enter your password',
      'forgotPass': 'Forgot Password?',
      'login': 'Login',
      'noAccount': 'Don’t have an account? ',
      'registerNow': 'Register Now',
      // Register
      'helloRegister': 'Hello! \nRegister to get started',
      'pass': 'Password',
      'confirmPass': 'Confirm password',
      'register': 'Register',
      'accountAlready': 'Already have an account? ',
      'loginNow': 'Login Now',
      // Navigation Bar
      'about': 'About',
      'navigation': 'Navigation',
      'profile': 'Profile',
    },
    'pt': {
      // About
      'why': 'Por quê',
      'how': 'Como',
      'who': 'Quem',
      // Profile & Edit Profile w/ Snackbars
      'username': 'Carregando...',
      'country': 'Carregando...',
      'level': 'Nível',
      'totalKm': 'Total km',
      'places': 'Lugares',
      'signOut': 'Sair',
      'signOutConfirmation': 'Tem certeza de que deseja sair?',
      'cancel': 'Cancelar',
      'deleteAccount': 'Excluir conta',
      'enterPassword': 'Digite sua senha para confirmar a exclusão da conta.',
      'password': 'Senha',
      'delete': 'Excluir',
      'passwordRequired': 'A senha é necessária para excluir sua conta.',
      'updateFailed': 'Falha na atualização',
      'statistics': 'Estatísticas',
      'viewRouteHistory': 'Ver histórico de rotas >',
      'preferences': 'Preferências',
      'allowNotifications': 'Permitir notificações',
      'onlyLowRisk': 'Apenas rotas de baixo risco',
      'changeRoute': 'Alterar rota automaticamente',
      'unitMeasure': 'Unidade de medida',
      'riskAlertDistance': 'Distância do alerta de risco',
      'what': 'O que é isso?',
      'riskAlertDistanceInfo': 'Esta configuração determina a distância na qual você receberá uma notificação sobre zonas de risco próximas. Escolha uma distância menor para alertas precisos ou uma maior para avisos antecipados.',
      'reRouteAlertDistance': 'Distância do alerta de re-rota',
      'reRouteAlertDistanceInfo': 'Esta configuração determina a distância na qual você receberá uma notificação sobre oportunidades de re-rota próximas. Escolha uma distância menor para alertas precisos ou uma maior para avisos antecipados.',
      'language': 'Idioma',
      'speciesForAlerts': 'Selecionar espécies para alertas',
      'settings': 'Configurações',
      'editProfile': 'Editar perfil',
      'info' : 'Informação',
      'amphibians': 'Anfíbios',
      'reptiles': 'Répteis',
      'hedgehogs': 'Ouriços',
      'enterUsername': 'Nome de utilizador',
      'enterEmail': 'Email',
      'enterCountry': 'País',
      'passwordUpdated': 'Senha atualizada com sucesso!',
      'errorFetchingProfile': 'Erro ao buscar o perfil:',
      'profileUpdated': 'Perfil atualizado com sucesso!',
      'errorUpdatingProfile': 'Erro ao atualizar o perfil:',
      'selectProfile': 'Selecionar imagem de perfil',
      'currentPass': 'Senha atual',
      'enterCurrent': 'Digite a senha atual',
      'newPass': 'Nova senha',
      'enterNew': 'Digite a nova senha',
      'update': 'Atualizar',
      'profileDeleted': 'Conta excluída com sucesso.',
      // Home
      "errorFetchingRoute": "Erro ao obter rota:",
      "failFetchingRoute": "Falha ao obter rota",
      "errorFetchingCoordinates": "Erro ao obter coordenadas",
      "errorFetchingSuggestions": "Erro ao obter sugestões",
      "errorFetchingPreferences": "Erro ao obter preferências",
      "enterDestination": "Digite o destino",
      "setDestination": "Definir destino",
      "highProbability": "Alta probabilidade de encontrar",
      "mediumProbability": "Média probabilidade de encontrar",
      "unknown": "Desconhecido",
      "switchRoute": "Alterar rota",
      // Login
      "start": "Iniciar",
      'welcome': 'Bem-vindo de volta!\nQue bom vê-lo novamente!',
      'inputEmail': 'Digite o seu e-mail',
      'pleaseEmail': 'Por favor, insira o seu e-mail',
      'userPass': 'Digite a sua senha',
      'pleasePass': 'Por favor, insira a sua senha',
      'forgotPass': 'Esqueceu-se da senha?',
      'login': 'Entrar',
      'noAccount': 'Não tem uma conta? ',
      'registerNow': 'Cadastre-se agora',
      // Register
      'helloRegister': 'Olá! \nCadastre-se para começar',
      'pass': 'Senha',
      'confirmPass': 'Confirmar senha',
      'register': 'Cadastrar',
      'accountAlready': 'Já tem uma conta? ',
      'loginNow': 'Entrar agora',
      // Navigation Bar
      'about': 'Sobre',
      'navigation': 'Navegação',
      'profile': 'Perfil'
    },
    'es': {
      // About
      'why': 'Por qué',
      'how': 'Cómo',
      'who': 'Quién',
      // Profile & Edit Profile w/ Snackbars
      'username': 'Cargando...',
      'country': 'Cargando...',
      'level': 'Nivel',
      'totalKm': 'Kilómetros totales',
      'places': 'Lugares',
      'signOut': 'Cerrar sesión',
      'signOutConfirmation': '¿Estás seguro de que deseas cerrar sesión?',
      'cancel': 'Cancelar',
      'deleteAccount': 'Eliminar cuenta',
      'enterPassword': 'Introduce tu contraseña para confirmar la eliminación de la cuenta.',
      'password': 'Contraseña',
      'delete': 'Eliminar',
      'passwordRequired': 'Se requiere contraseña para eliminar tu cuenta.',
      'updateFailed': 'Error en la actualización',
      'statistics': 'Estadísticas',
      'viewRouteHistory': 'Ver historial de rutas >',
      'preferences': 'Preferencias',
      'allowNotifications': 'Permitir notificaciones',
      'onlyLowRisk': 'Solo rutas de bajo riesgo',
      'changeRoute': 'Cambiar ruta automáticamente',
      'unitMeasure': 'Unidad de medida',
      'riskAlertDistance': 'Distancia de alerta de riesgo',
      'what': '¿Qué es esto?',
      'riskAlertDistanceInfo': 'Esta configuración determina la distancia a la que recibirás una notificación sobre zonas de riesgo próximas. Elige una distancia menor para alertas precisas o una mayor para advertencias anticipadas.',
      'reRouteAlertDistance': 'Distancia de alerta de re-ruta',
      'reRouteAlertDistanceInfo': 'Esta configuración determina la distancia a la que recibirás una notificación sobre oportunidades de re-ruta próximas. Elige una distancia menor para alertas precisas o una mayor para advertencias anticipadas.',
      'language': 'Idioma',
      'speciesForAlerts': 'Seleccionar especies para alertas',
      'settings': 'Configuraciones',
      'editProfile': 'Editar perfil',
      'info' : 'Información',
      'amphibians': 'Anfibios',
      'reptiles': 'Reptiles',
      'hedgehogs': 'Erizos',
      'enterUsername': 'Nombre de usuario',
      'enterEmail': 'Correo electrónico',
      'enterCountry': 'País',
      'passwordUpdated': '¡Contraseña actualizada con éxito!',
      'errorFetchingProfile': 'Error al obtener el perfil:',
      'profileUpdated': '¡Perfil actualizado con éxito!',
      'errorUpdatingProfile': 'Error al actualizar el perfil:',
      'selectProfile': 'Seleccionar imagen de perfil',
      'currentPass': 'Contraseña actual',
      'enterCurrent': 'Ingresa la contraseña actual',
      'newPass': 'Nueva contraseña',
      'enterNew': 'Ingresa la nueva contraseña',
      'update': 'Actualizar',
      'profileDeleted': 'Cuenta eliminada con éxito.',
      // Home
      "errorFetchingRoute": "Error al obtener la ruta:",
      "failFetchingRoute": "Error al obtener la ruta",
      "errorFetchingCoordinates": "Error al obtener coordenadas",
      "errorFetchingSuggestions": "Error al obtener sugerencias",
      "errorFetchingPreferences": "Error al obtener preferencias",
      "enterDestination": "Ingrese destino",
      "setDestination": "Establecer destino",
      "highProbability": "Alta probabilidad de encontrar",
      "mediumProbability": "Probabilidad media de encontrar",
      "unknown": "Desconocido",
      "switchRoute": "Cambiar ruta",
      "start": "Iniciar",
      // Login
      'welcome': '¡Bienvenido de nuevo!\n¡Qué bueno verte otra vez!',
      'inputEmail': 'Ingresa tu correo electrónico',
      'pleaseEmail': 'Por favor, ingresa tu correo electrónico',
      'userPass': 'Ingresa tu contraseña',
      'pleasePass': 'Por favor, ingresa tu contraseña',
      'forgotPass': '¿Olvidaste tu contraseña?',
      'login': 'Iniciar sesión',
      'noAccount': '¿No tienes una cuenta? ',
      'registerNow': 'Regístrate ahora',
      // Register
      'helloRegister': '¡Hola! \nRegístrate para empezar',
      'pass': 'Contraseña',
      'confirmPass': 'Confirmar contraseña',
      'register': 'Registrarse',
      'accountAlready': '¿Ya tienes una cuenta? ',
      'loginNow': 'Inicia sesión ahora',
      // Navigation Bar
      'about': 'Acerca de',
      'navigation': 'Navegación',
      'profile': 'Perfil'
    },
  };

  // Get the localized string based on selected language
  static String getLocalizedString(String languageCode, String key) {
    return translations[languageCode]?[key] ?? key;
  }
}
