class LanguageConfig {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'username': 'Loading...',
      'country': 'Loading...',
      'level': 'Level',
      'totalKm': 'Total km',
      'places': 'Places',
      'why': 'Why',
      'how': 'How',
      'who': 'Who',
      'signOut': 'Sign Out',
      'signOutConfirmation': 'Are you sure you want to sign out?',
      'cancel': 'Cancel',
      'deleteAccount': 'Delete Account',
      'enterPassword': 'Please enter your password to confirm account deletion.',
      'password': 'Password',
      'delete': 'Delete',
      'passwordRequired': 'Password is required to delete your account.',
      'updateFailed': 'Update failed',
      'statistics': 'Statistics',
      'viewRouteHistory': 'View route history >',
      'preferences': 'Preferences',
      'allowNotifications': 'Allow notifications',
      'onlyLowRisk': 'Only low risk route',
      'changeRoute': 'Change route automatically',
      'unitMeasure': 'Unit of measure',
      'riskAlertDistance': 'Risk alert distance',
      'what': 'What is this?',
      'riskAlertDistanceInfo': 'This setting determines the distance at which you will receive a notification about upcoming risk zones. Choose a smaller distance for precise alerts or a larger distance for early warnings.',
      'reRouteAlertDistance': 'Re-route alert distance',
      'reRouteAlertDistanceInfo': 'This setting determines the distance at which you will receive a notification about upcoming Re-route opportunities. Choose a smaller distance for precise alerts or a larger distance for early warnings.',
      'language': 'Language',
      'speciesForAlerts': 'Select Species for Alerts',
      'settings': 'Settings',
      'editProfile': 'Edit Profile',
      'info' : 'Information',
      'amphibians' : 'Amphibians',
      'reptiles' : 'Reptiles',
      'hedgehogs' : 'Hedgehogs',
    },
    'pt': {
      'username': 'Carregando...',
      'country': 'Carregando...',
      'level': 'Nível',
      'totalKm': 'Total km',
      'places': 'Lugares',
      'why': 'Por quê',
      'how': 'Como',
      'who': 'Quem',
      'signOut': 'Sair',
      'signOutConfirmation': 'Tem certeza de que deseja sair?',
      'cancel': 'Cancelar',
      'deleteAccount': 'Excluir conta',
      'enterPassword': 'Digite sua senha para confirmar a exclusão da conta.',
      'password': 'Senha',
      'delete': 'Excluir',
      'passwordRequired': 'A senha é necessária para excluir sua conta.',
      'updateFailed': 'Falha na atualização',
      'statistics': 'Estatísticas',
      'viewRouteHistory': 'Ver histórico de rotas >',
      'preferences': 'Preferências',
      'allowNotifications': 'Permitir notificações',
      'onlyLowRisk': 'Apenas rotas de baixo risco',
      'changeRoute': 'Alterar rota automaticamente',
      'unitMeasure': 'Unidade de medida',
      'riskAlertDistance': 'Distância do alerta de risco',
      'what': 'O que é isso?',
      'riskAlertDistanceInfo': 'Esta configuração determina a distância na qual você receberá uma notificação sobre zonas de risco próximas. Escolha uma distância menor para alertas precisos ou uma maior para avisos antecipados.',
      'reRouteAlertDistance': 'Distância do alerta de re-rota',
      'reRouteAlertDistanceInfo': 'Esta configuração determina a distância na qual você receberá uma notificação sobre oportunidades de re-rota próximas. Escolha uma distância menor para alertas precisos ou uma maior para avisos antecipados.',
      'language': 'Idioma',
      'speciesForAlerts': 'Selecionar espécies para alertas',
      'settings': 'Configurações',
      'editProfile': 'Editar perfil',
      'info' : 'Informação',
      'amphibians': 'Anfíbios',
      'reptiles': 'Répteis',
      'hedgehogs': 'Ouriços',
    },
    'es': {
      'username': 'Cargando...',
      'country': 'Cargando...',
      'level': 'Nivel',
      'totalKm': 'Kilómetros totales',
      'places': 'Lugares',
      'why': 'Por qué',
      'how': 'Cómo',
      'who': 'Quién',
      'signOut': 'Cerrar sesión',
      'signOutConfirmation': '¿Estás seguro de que deseas cerrar sesión?',
      'cancel': 'Cancelar',
      'deleteAccount': 'Eliminar cuenta',
      'enterPassword': 'Introduce tu contraseña para confirmar la eliminación de la cuenta.',
      'password': 'Contraseña',
      'delete': 'Eliminar',
      'passwordRequired': 'Se requiere contraseña para eliminar tu cuenta.',
      'updateFailed': 'Error en la actualización',
      'statistics': 'Estadísticas',
      'viewRouteHistory': 'Ver historial de rutas >',
      'preferences': 'Preferencias',
      'allowNotifications': 'Permitir notificaciones',
      'onlyLowRisk': 'Solo rutas de bajo riesgo',
      'changeRoute': 'Cambiar ruta automáticamente',
      'unitMeasure': 'Unidad de medida',
      'riskAlertDistance': 'Distancia de alerta de riesgo',
      'what': '¿Qué es esto?',
      'riskAlertDistanceInfo': 'Esta configuración determina la distancia a la que recibirás una notificación sobre zonas de riesgo próximas. Elige una distancia menor para alertas precisas o una mayor para advertencias anticipadas.',
      'reRouteAlertDistance': 'Distancia de alerta de re-ruta',
      'reRouteAlertDistanceInfo': 'Esta configuración determina la distancia a la que recibirás una notificación sobre oportunidades de re-ruta próximas. Elige una distancia menor para alertas precisas o una mayor para advertencias anticipadas.',
      'language': 'Idioma',
      'speciesForAlerts': 'Seleccionar especies para alertas',
      'settings': 'Configuraciones',
      'editProfile': 'Editar perfil',
      'info' : 'Información',
      'amphibians': 'Anfibios',
      'reptiles': 'Reptiles',
      'hedgehogs': 'Erizos',
    },
  };

  // Get the localized string based on selected language
  static String getLocalizedString(String languageCode, String key) {
    return translations[languageCode]?[key] ?? key;
  }
}
